project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
base_path: src/main/resources

files:
  - source: /messages/messages.en-US.yml
    translation: /messages/messages.%locale%.yml

  - source: /web/i18n/app/en-US.json
    translation: /web/i18n/app/%locale%.json

  - source: /web/i18n/admin/en-US.json
    translation: /web/i18n/admin/%locale%.json

  - source: /web/i18n/help/en-US.json
    translation: /web/i18n/help/%locale%.json

  - source: /web/i18n/market-algorithms/en-US.json
    translation: /web/i18n/market-algorithms/%locale%.json

  - source: /web/i18n/materials/en-US.json
    translation: /web/i18n/materials/%locale%.json
