# Keep the plugin entry point referenced by plugin.yml.
-keep public class com.webshopx.WebShopPlugin extends org.bukkit.plugin.java.JavaPlugin {
    public <init>();
    public void onEnable();
    public void onDisable();
}

# Bukkit discovers event handlers by annotation scanning.
-keepclassmembers class * implements org.bukkit.event.Listener {
    @org.bukkit.event.EventHandler <methods>;
}

# Preserve metadata commonly needed by Bukkit/Paper, records, and diagnostics.
-keepattributes *Annotation*,Signature,InnerClasses,EnclosingMethod,Record,Exceptions,SourceFile,LineNumberTable

# Keep enum helper methods used by generated bytecode.
-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}

# Suppress warnings for APIs provided by the server runtime or optional integrations.
-dontwarn org.bukkit.**
-dontwarn org.spigotmc.**
-dontwarn io.papermc.**
-dontwarn net.milkbowl.vault.**
