rootProject.name = 'WebShopX'

include 'webshopx-platform-api'
include 'webshopx-core'
include 'webshopx-testkit'
include 'webshopx-loader-stubs'
include 'webshopx-loader-runtime'
include 'webshopx-fixture-mod'
include 'webshopx-fabric-1182'
include 'webshopx-fabric-1201'
include 'webshopx-fabric-modern'
include 'webshopx-forge-1182'
include 'webshopx-forge-1201'
include 'webshopx-neoforge-1201'
include 'webshopx-neoforge-modern'
