modLoader="javafml"
loaderVersion="[46,)"
license="GPL-3.0-or-later"
[[mods]]
modId="webshopx"
version="${modVersion}"
displayName="WebShopX"
description='''Server-side WebShopX runtime for Forge'''
[[dependencies.webshopx]]
modId="minecraft"
mandatory=true
versionRange="${minecraftVersionRange}"
ordering="NONE"
side="SERVER"
