package com.webshopx;

enum AdminPermission {
  REDEEM_MANAGE,
  PRODUCT_MANAGE,
  PRODUCT_OFFLINE_INVENTORY_IMPORT,
  PRODUCT_ZERO_PRICE,
  ORDER_VIEW,
  ECONOMY_MANAGE,
  MARKET_MANAGE,
  USER_SUPPORT,
  AUDIT_VIEW,
  HOMEPAGE_MANAGE
}
