package com.webshopx;

enum AdminPermission {
  REDEEM_MANAGE,
  PRODUCT_MANAGE,
  PRODUCT_OFFLINE_INVENTORY_IMPORT,
  PRODUCT_ZERO_PRICE,
  ORDER_VIEW,
  ECONOMY_MANAGE,
  MARKET_MANAGE,
  USER_SUPPORT,
  AUDIT_VIEW,
  HOMEPAGE_MANAGE,
  PROMOTION_VIEW,
  PROMOTION_MANAGE,
  COUPON_MANAGE,
  COUPON_GRANT,
  COUPON_COMPENSATE,
  MEMBERSHIP_VIEW,
  MEMBERSHIP_MANAGE,
  MEMBERSHIP_GRANT,
  PROMOTION_FINANCE_VIEW,
  SELLER_PROMOTION_MODERATE,
  PROMOTION_EMERGENCY_STOP
}
