name: Test and Release

permissions:
  contents: write

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 0 * * 6'

concurrency:
  group: ${{ format('{0}-{1}', github.workflow, github.ref) }}
  cancel-in-progress: false

jobs:
  test:
    name: Run unit tests
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        java: [ 21 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Common Setup
        uses: ./.github/actions/common-setup
        with:
          java-version: ${{ matrix.java }}

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle (Ignoring Quality Checks)
        run: ./gradlew build --info -x checkstyleMain -x checkstyleTest -x spotbugsMain -x spotbugsTest

      - name: Upload build results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }} Java ${{ matrix.java }} build results
          path: ${{ github.workspace }}/build/libs/

      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }} Java ${{ matrix.java }} test results
          path: ${{ github.workspace }}/build/reports/

  release:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Common Setup
        uses: ./.github/actions/common-setup
        with:
          java-version: 21

      - name: Get short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle (Ignoring Quality Checks)
        run: |
          ./gradlew build -x checkstyleMain -x checkstyleTest -x spotbugsMain -x spotbugsTest \
          -Pversion="1.1.3-SNAPSHOT+${{ steps.vars.outputs.sha_short }}"

      - name: Upload build results
        uses: actions/upload-artifact@v4
        with:
          name: Dev Build
          path: ${{ github.workspace }}/build/libs/
          retention-days: 14

      - name: Create Dev Release (Current Repo)
        env:
          GH_TOKEN: ${{ github.token }} 
        run: |
          if gh release view dev >/dev/null 2>&1; then
            gh release upload dev ${{ github.workspace }}/build/libs/* --clobber
          else
            gh release create dev --generate-notes --prerelease --title "Dev Build" ${{ github.workspace }}/build/libs/*
          fi

      - name: Sync Release to Repo B
        env:
          GH_TOKEN: ${{ secrets.REPO_WebShopX_Issues_TOKEN }}
          TARGET_REPO: "Cc-Cece/WebShopX-Issues" 
        run: |
          echo "Syncing build artifacts to $TARGET_REPO..."
          if gh release view dev --repo "$TARGET_REPO" >/dev/null 2>&1; then
            gh release upload dev ${{ github.workspace }}/build/libs/* --repo "$TARGET_REPO" --clobber
          else
            gh release create dev --repo "$TARGET_REPO" --generate-notes --prerelease --title "Dev Build" ${{ github.workspace }}/build/libs/*
          fi